### ISSUE TITLE
Azure tags endpoint creates multiple entries for the same tag key

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku#1486]
**Describe the bug**
Adding an azure provider with multiple tag values with the same tag key value causes us to generate a new tag key value for every tag. We should really be grouping all tags under the same shared tag key value.

**To Reproduce**
1. Go to 'api/cost-management/v1/providers/'
2. Add azure provider with multiple tags sharing the same tag key
3. See 'api/cost-management/v1/tags/azure/'

```
"data": [
        {
            "key": "project",
            "values": [
                "p1"
            ]
        },
        {
            "key": "project",
            "values": [
                "p2"
            ]
        },
        {
            "key": "project",
            "values": [
                "p3"
            ]
        },
        {
            "key": "openshift_project",
            "values": [
                "test_victor"
            ]
        },
        {
            "key": "environment",
            "values": [
                "alpha"
            ]
        },
        {
            "key": "environment",
            "values": [
                "bravo"
            ]
        },
```

**Expected behavior**
All tags that have the same key value should be shown in a list under that key value.

**Context (please complete the following information):**
 - OS: Fedora
 - Browser: Firefox
 - Commit Hash from status endpoint: 776278675649b0f439bc4afce28482564df825cf

**Additional context**
I was producing this locally and on CI with nise data.

Similar things happen on the tags/openshift/infrastructures/azure/ but my guess is its all the same issue.

Feel free to use my static yaml
```
---
generators:
  - BandwidthGenerator:
      start_date: today
      meter_id: 55555555-4444-3333-2222-111111111112
      resource_location: "US East"
      resource_rate: 2
      usage_quantity: 2
      tags: {"openshift_project":"test_victor", "environment": "alpha", "project":"p1"}
  - SQLGenerator:
      start_date: today
      meter_id: 55555555-4444-3333-2222-111111111114
      resource_location: "US South Central"
      resource_rate: 2
      usage_quantity: 3
      tags: {"openshift_project":"test_victor", "environment": "bravo", "project":"p2"}
      additional_info: {"ConsumptionMeter": "1111aaaa-22bb-33cc-44dd-555555eeeeee"}
  - StorageGenerator:
      start_date: today
      meter_id: 55555555-4444-3333-2222-111111111116
      resource_location: "US North Central"
      resource_rate: 2
      usage_quantity: 4
      instance_id: '/subscriptions/99999999-9999-9999-9999-999999999981/resourceGroups/koku-99hqd-rg/providers/Microsoft.Compute/virtualMachines/pvc_azure_victor'
      tags: {"environment": "charlie", "project":"p3"}
      additional_info: {"ConsumptionMeter": "1111aaaa-22bb-33cc-44dd-555555eeeeee"}
  - VMGenerator:
      start_date: today
      meter_id: 55555555-4444-3333-2222-111111111118
      resource_location: "US West"
      resource_rate: 2
      usage_quantity: 5
      instance_id: '/subscriptions/99999999-9999-9999-9999-999999999981/resourceGroups/koku-99hqd-rg/providers/Microsoft.Compute/virtualMachines/test_azure_victor'
      tags: {"environment": "delta", "project":"p3"}
      additional_info: {"ConsumptionMeter": "1111aaaa-22bb-33cc-44dd-555555eeeeee"}
  - VNGenerator:
      start_date: today
      # product_family: DNS Query
      tags: {"openshift_project":"test_victor", "app":"analytics"}


# SubscriptionGuid
accounts:
  payer: 38f1d748-3ac7-4b7f-a5ae-8b5ff16db82c
  user:
    - 38f1d748-3ac7-4b7f-a5ae-8b5ff16db82c
```
